### ISSUE TITLE
How to disable HMR

### ISSUE THREAD

**Issue by lmj0011** [nuxt/adonuxt#11]
I'm having some issues logging into my app, basically everytime I log in , the app refreshes and doesn't auth the user (it takes a few log in attempts for it actually log the user in).

I want to disable Hot Module Reloading, to rule it out as the problem.

**Comment by lmj0011** [comment]
running `npm start` to start the server in production, omits HMR

**Comment by Atinux** [comment]
I don't think the hot reloading is an issue since it's only when you update your code.

**Comment by lmj0011** [comment]
@Atinux https://github.com/nuxt/adonuxt/issues/12
