### ISSUE TITLE
Authetication on nuxtjs not working

### ISSUE THREAD

**Issue by Geowan** [nuxt/adonuxt#113]
Am trying to authenticate with adonixjs jwt like this 
 
       const user = await User.query()
            .where('email', email)
            .first()
       let passwordVerified = await Hash.verify( password,user.password)
        console.log(passwordVerified) //this is always false

The above always returns false. I have also noted the hash.js file is missing. How do i resolve this

I have also asked the question at stackoverflow at [this link](https://stackoverflow.com/questions/52688463/adonijs-authentication-fails-with-401-error-with-corect-email-and-password)

<div align="right"><sub><em>This question is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/adonuxt-template/issues/c91">#c91</a>)</em></sub></div>

**Comment by ghost** [comment]
This issue as been imported as [question](https://cmty.app/nuxt/adonuxt-template/issues/c91) since it does not respect [adonuxt-template issue template](https://cmty.app/nuxt/issues/new?repo=adonuxt-template). Only bug reports and feature requests stays open to reduce maintainers workload.
			If your issue is not a question, please mention the repo admin or moderator to change its type and it will be re-opened automatically.
			Your question is available at [https://cmty.app/nuxt/adonuxt-template/issues/c91](https://cmty.app/nuxt/adonuxt-template/issues/c91).

**Comment by Geowan** [comment]
why is this closed yet hashing fails?

**Comment by woodgates** [comment]
Hi the problem are the sessions. Session info doesnt persist.
