### ISSUE TITLE
Adonuxt deprecated

### ISSUE THREAD

**Issue by Sjoerd** [nuxt/adonuxt#125]
What? 
Why is this deprecated? 
What can I use instead of this?
I love Adonuxt <3 

<div align="right"><sub><em>This question is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/adonuxt-template/issues/c102">#c102</a>)</em></sub></div>

**Comment by atinux** [comment]
Hi @Sjoerrdd 

Actually it's deprecated in favour of the new Nuxt services API coming soon to work with API servers separated from Nuxt.js process for better performances.
