### ISSUE TITLE
I can't access req.session in fetch method

### ISSUE THREAD

**Issue by BRKsDeadPool** [nuxt/adonuxt#13]
In express i could use req.session.paramName, but now with adonuxt doesn't works

**Comment by lmj0011** [comment]
https://nuxtjs.org/api/pages-fetch

based on the example, inside the `fetch` func, you should be able to use `params`

**Comment by BRKsDeadPool** [comment]
i'm using the "req" on vuex nuxtInitServer({ commit }, { req}), like on the docs example

**Comment by lmj0011** [comment]
you should find your answer here: 
https://github.com/nuxt/adonuxt/issues/6
