### ISSUE TITLE
Middleware for Authed Nuxt Routes

### ISSUE THREAD

**Issue by cloudratha** [nuxt/adonuxt#15]
In the scope of Nuxt, I'm battling to get my "auth" middleware to attach to a page.

I have setup the following: `resources/middleware/auth.js`

I have tried to attach the middleware to the page vue file with no result.

    //resources/pages/users/create.vue
    ...
    <script>
        export default {
            middleware: 'auth'
        }
    </script>

My store.state.authUser is set to null in Vue Dev Tools so the user isn't authenticated.
Also I don't see the middleware compiling through webpack.

Any thoughts?

**Comment by cloudratha** [comment]
Ah, I see the feature is pretty brand new. 
Any idea when it will be released as a tag?

**Comment by alexchopin** [comment]
Probably next week

**Comment by Atinux** [comment]
@cloudratha you can now update nuxt to `0.9.8` and use the middleware 👍
