### ISSUE TITLE
Making API calls to AdonisJS

### ISSUE THREAD

**Issue by deyceg** [nuxt/adonuxt#18]
I've probably missed something, but seeing as there is a catch all route defined for the NuxtController if you post/get to any url e.g an API call its going to try and serve up a page instead.

How do you separate your client requests from your server requests?

The only thing I can find is to use Route.group to create an an subdomain for api requests

```
Route.group('api', function() {
  Route.post('login', 'UsersController.login')
}).domain('api')
```

**Comment by alexchopin** [comment]
Hi, you only need to create routes before [Nuxt routes](https://github.com/nuxt/adonuxt/blob/master/app/Http/routes.js#L20) in `app/Http/routes.js` file for your API.

**Comment by deyceg** [comment]
@alexchopin Thanks for the prompt response! Maybe I could create an ApiController or such? This would guarantee some level of isolation between client-side routing and server-side routing instead of relying on ordering of routes that serve different purposes!

**Comment by deyceg** [comment]
Seems i'm having problems even configuring a simple route and curling it :/ Seems to be registered but i'm not seeing the controller method firing:

```
const Route = use('Route')

Route.group('v1', () => {
  Route.post('/login', 'LoginController.login')
}).prefix('/api/v1')

Route.get('*', 'NuxtController.render')

'use strict'

class LoginController {

  * login (request, response) {
    console.log('login api');
    const email = request.input('email')
    const password = request.input('password')
    const login = yield request.auth.attempt(email, password)

    if (login) {
      response.send('Logged In Successfully')
      return
    }

    response.unauthorized('Invalid credentails')
  }

}

module.exports = LoginController
```
