### ISSUE TITLE
Update to latest version

### ISSUE THREAD

**Issue by deyceg** [nuxt/adonuxt#19]
Seems we're out of date!

Compare:
https://github.com/adonisjs/adonis-app/blob/develop/app/Listeners/Http.js

With:
https://github.com/nuxt/adonuxt/blob/master/app/Listeners/Http.js

For whatever reason, it was swallowing any uncaught exceptions.

**Comment by Atinux** [comment]
It's done!

See https://github.com/nuxt/adonuxt/commit/ba022a2874321db9faedaa5c26efd9b6943d8a86

**Comment by lmj0011** [comment]
https://github.com/nuxt/adonuxt/pull/20
