### ISSUE TITLE
example of using nuxt & adonis api together

### ISSUE THREAD

**Issue by ziyaaktas** [nuxt/adonuxt#24]
is there an example of using adonis as the renderer & api?

**Comment by Atinux** [comment]
Hi @ziyaaktas 

I recommend you to read the [AdonisJS documentation](http://adonisjs.com/docs/3.2/overview).

It's really easy to use and well documented. Then, you can call this routes with axios from your nuxt.js application, you can take a look the [express starter]() to see how to do:

1. [pages/index.vue](https://github.com/nuxt/express/blob/master/template/pages/index.vue)
2. [plugins/axios.js](https://github.com/nuxt/express/blob/master/template/plugins/axios.js)
3. [nuxt.config.js line 24)(https://github.com/nuxt/express/blob/master/template/nuxt.config.js#L24)

**Comment by ziyaaktas** [comment]
The links you mentioned are using express actually.  So Adonis is only being used as a renderer?

**Comment by alexchopin** [comment]
Adonis is used for both like the express template example.
You only need to create routes and controllers in your adonis project for handle your API.

**Comment by sergiocastrovale** [comment]
I'm actually porting a project from using the express boilerplate into Adonuxt and I'm unable to use plugins/*. I always get ES6-related compilation errors (`unexpected token import` and the like).

Do I need to configure anything for ES6 to be transpiled and things to work out of the box?
