### ISSUE TITLE
sass-loader

### ISSUE THREAD

**Issue by alphaelf** [nuxt/adonuxt#3]
hi, can i use `<style lang="scss">` in `*.vue` files?
it's throw this error:
> Module not found: Error: Can't resolve 'sass-loader' in '..\resources\pages'

and the guides says it must add to `webpack.config.js` but i can't find it!

should i create it? or is another solution?

**Comment by Atinux** [comment]
Hi @alphaelf 

You need to install `sass-loader` and `node-sass` and nuxt.js will handle the `scss` lang in your `.vue` file automatically:

```bash
npm install --save-dev node-sass sass-loader
```

**Comment by alphaelf** [comment]
tanks
