### ISSUE TITLE
Render Request executed multiple times?

### ISSUE THREAD

**Issue by FrancosLab** [nuxt/adonuxt#30]
If you add a simple console.log to the nuxt controller render, it will be executed multiple times.

```
  * render (request, response) {
    console.log('request');
    this.nuxt.render(request.request, response.response)
  }
```

when you load the home page, and check the shell output you get.

```
request
request
request
request
request
request
request
request
```

Is there a specific reason why this is happening? or is this a bug? One of the biggest problem with this, is that which each time this generator function runs, a new CSRF token will be generated by adonisjs but the rendered page, will only receive the first generated token.

**Comment by Atinux** [comment]
Indeed, `nuxt.render` handle the static handling for the nuxt bundle and the `public` folder, nothing to worry about it :)
