### ISSUE TITLE
Example of using nuxt & adonis api with Auth api Middleware

### ISSUE THREAD

**Issue by cawa-93** [nuxt/adonuxt#32]
Earlier you provided an [example](https://github.com/nuxt/adonuxt/issues/24) of appealing to the api. But there is a difficulty: to access the api point you need to be authorized. 
```javascript
Route.group('api', () => {
  Route.resource('users', 'UsersController')
  Route.resource('pages', 'PagesController')
})
.middleware('auth')
```
On the client side, everything works, but on the server side - I get an error
```html
<template>
<div>{{users}}</div>
</template>

<script>
import axios from '~plugins/axios'

export default {
  async data ({error, req}) {
    const { data } = await axios.get('/api/v1/users.json')
    return {
      users: data
    }
  },
  // async mounted () {
  //  const { data } = await axios.get('api/v1/users.json')
  //  this.users = data
  // }
}
</script>
```

**Comment by Atinux** [comment]
Hi @cawa-93 

What session provider do your use to authorise the user?

If it's the cookies, you might need to give the cookies of the use you get from `req.headers.cookie`.

See https://github.com/mzabriskie/axios/issues/560#issuecomment-263998958 which might help.

**Comment by cawa-93** [comment]
@Atinux, Thanks! The following code work:
```javascript
import axios from '~plugins/axios'

export default {
  async data ({error, req}) {
    let options = {}
    if (req && req.headers) {
      options.headers = req.headers
    }
    const { data } = await axios.get('/api/v1/users.json', options)
    return {
      users: data
    }
  }
}
```
But here's the question: is it possible to somehow write this code:
```javascript
if (req && req.headers) {
  options.headers = req.headers
}
```
 in the plugin `/resources/plugins/axios.js`, so as not to duplicate it for each page? In other words, how to access the request object inside the plugin
```javascript
import axios from 'axios'

let options = {}
// The server-side needs a full url to works
if (process.SERVER_BUILD) {
	options.baseURL = `http://${process.env.HOST || 'localhost'}:${process.env.PORT || 3000}`
	options.headers = req.headers // req = undefined
}

export default axios.create(options)
```

**Comment by Atinux** [comment]
@cawa-93 it's not possible to access `req` in the plugin directly, but you can do something like this:

`plugins/axios.js`
```js
import axios from 'axios'

export default function (req) {
  let options = {}
  // The server-side needs a full url to works
  if (process.SERVER_BUILD) {
    options.baseURL = `http://${process.env.HOST || 'localhost'}:${process.env.PORT || 3000}`
    options.headers = req.headers
  }
  return axios.create(options)
}
```

And then, in your page components:
```js
import axios from '~plugins/axios'

export default {
  async data ({error, req}) {
    const { data } = await axios(req).get('/api/v1/users.json')
    return {
      users: data
    }
  }
}
```

You can also give the full context, but I believe req is the only one you really need for axios.

**Comment by lmj0011** [comment]
https://github.com/nuxt/adonuxt/issues/32#issuecomment-287322352

cool, this works

**Comment by abelmq** [comment]
Please, I have tried to follow the recommended steps, however I have an error when configuring

`import axios from '~ plugins / axios'
`
```
This dependency was not found:

* ~plugins/axios in ./node_modules/babel-loader/lib? ...

To install it, you can run: npm install --save ~plugins/axios
```

in spite of having configured in /config/nuxt.js

```
build: {
    vendor: ['axios']
  },
  plugins: ['~plugins/axios.js'],
```

What is missing?

**Comment by Atinux** [comment]
@abelmq `~plugins` does not work anymore, use `~/plugins/axios`

**Comment by abelmq** [comment]
@Atinux is correct! Thank you very much.

**Comment by alanaasmaa** [comment]
@Atinux Hi, i dont understand at all that async part of data.

How and where can i use this. Where does the error and req param come from. Which framework defines them. Google is not a mate in these stuff. I can't find anything on any documentation.

```
  async data ({error, req}) {
    const { data } = await axios(req).get('/api/v1/users.')
    return {
      users: data
    }
  }
```
I cannot use  {{ users }} in my template, why is that so ?

How is this different with nuxt asyncData method and which one i should use for which case ?
