### ISSUE TITLE
Adonuxt + Adonis-ally

### ISSUE THREAD

**Issue by lmj0011** [nuxt/adonuxt#33]
I'm stuck on getting Adonis-ally to work with Adonuxt.
http://adonisjs.com/docs/3.2/social-auth

I'm having an issue in rendering the view in the `handleCallback`

```js
* providerHandleCallback (request, response) {
    const provider = request.param('provider')
    const socialAuthUser = yield request.ally.driver(provider).getUser()

    console.log(socialAuthUser)
    const searchAttr = {
      email: socialAuthUser.getEmail()
    }

    const newUser = {
      email: socialAuthUser.getEmail(),
      username: socialAuthUser.getName(),
      auth_provider: provider,
      auth_provider_id: socialAuthUser.getId()
    }

    const user = yield User.findOrCreate(searchAttr, newUser)

    request.auth.loginViaId(user.id)

    // not sure what to do here, in order to get back to '/' with the authenticated user
    request.request.auth = request.auth
    request.request.auth.user = user
    return this.nuxt.renderRoute('/')
    ///////
  }
``` 
How would this be accomplished?

**Comment by lmj0011** [comment]
I'm thinking I would need to create a view for the `providerHandleCallback` route and just have it redirect it to `/`. That's the only possible workaround I can think of

**Comment by Atinux** [comment]
@lmj0011 can you try:

```js
request.request.auth = request.auth
request.request.auth.user = user
this.nuxt.renderRoute('/', { req: request.request, res: response.response })
.then(( html }) => {
  response.send(html)
})
```

But you might want to use the sessions in order to use `res.redirect('/')` instead and keep the user session even if the user refresh the page.

**Comment by lmj0011** [comment]
@Atinux 

>But you might want to **use the sessions** in order to use res.redirect('/') instead and keep the user session even if the user refresh the page.

Could you expand on what you mean by this?

**Comment by Atinux** [comment]
Try first to configure the sessions for your project: http://adonisjs.com/docs/3.2/sessions

Then, you should be able to stick the auth user via `request.session.put('user', user)`

**Comment by lmj0011** [comment]
@Atinux 

I cannot get this to work in my project.

Would you be able to set up a working example for adonuxt?

**Comment by lmj0011** [comment]
@Atinux 

???

**Comment by binler** [comment]
`request.request.auth = request.auth
request.request.auth.user = user
this.nuxt.renderRoute('/', { req: request.request, res: response.response })
.then(( html }) => {
  response.send(html)
})`
It's not working.

**Comment by cawa-93** [comment]
This work for my
```js
* handleCallback (request, response) {
	const fbUser = yield request.ally.driver('facebook').getUser()
	const newUser = {/* ... */}
	try {
		yield request.auth.loginViaId(newUser.id)
		response.redirect('/')
	} catch (e) {
		yield request.with({error: e.message}).flash()
		response.send({error: e.message})
	}
}
```

**Comment by binler** [comment]
@cawa-93 not work for me.
report this Error: `(node:13840) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: D:\\binler\\Adonis\\adocms\\D:\\binler\\Adonis\\adocms\\.nuxt\\components contains invalid WIN32 path characters.`

**Comment by ChangJoo-Park** [comment]
@binler Did you resolve this issue?
