### ISSUE TITLE
Adonis Model + Nuxt

### ISSUE THREAD

**Issue by paulopmx** [nuxt/adonuxt#35]
How do I pass model data to Nuxt?

Can I still use Lucid?

**Comment by alexchopin** [comment]
Can you explain more?

**Comment by Glutnix** [comment]
Because Nuxt pages have to work both server and client side, I think you want to use something like Axios to talk to regular Adonis HTTP API endpoints you make. In those controllers you can use Lucid ORM to do things with your database models :)

**Comment by Glutnix** [comment]
Thinking about this... because Adonis' leading philosophy is "Conventions Over Configuration", should Adonuxt follow suit and bundle something like Axios and provide a rudimentary working example?

**Comment by paulopmx** [comment]
Yeah. Bundles and examples would be great.

Also, wouldn't calling another route to pass the data add to the load times?

Paulo P. Mariñas Code Ninja https://codeninja.co
On Sat, Apr 1, 2017 at 5:00 PM, Brett Taylor <notifications@github.com> wrote:
Thinking about this... because Adonis' leading philosophy is "Conventions Over Configuration", should Adonuxt follow suit and bundle something like Axios and provide a rudimentary working example?

**Comment by paulopmx** [comment]
It'd be much simpler if nuxt can just call on the lucid orm.

Paulo P. Mariñas Code Ninja https://codeninja.co
On Sat, Apr 1, 2017 at 5:58 PM, Paulo Mariñas <paulopmx@gmail.com> wrote:

Yeah. Bundles and examples would be great.

Also, wouldn't calling another route to pass the data add to the load times?

Paulo P. Mariñas Code Ninja https://codeninja.co
On Sat, Apr 1, 2017 at 5:00 PM, Brett Taylor <notifications@github.com> wrote:
Thinking about this... because Adonis' leading philosophy is "Conventions Over Configuration", should Adonuxt follow suit and bundle something like Axios and provide a rudimentary working example?

**Comment by Atinux** [comment]
Nuxt.js purpose is UI rendering while abstracting away the client/server distribution.

You should use axios to call your own API based on AdonisJS, the only downside might me the first render on the server-side but it should not be perceptible.
