### ISSUE TITLE
How to use jquery here? 

### ISSUE THREAD

**Issue by stepheljobs** [nuxt/adonuxt#39]
I am always receiving this kind of errors whenever i use jquery.
> Error: jQuery requires a window with a document

Thanks everyone.

**Comment by InstanceOfMichael** [comment]
Tell us more about what you need jQuery for? We would like to be able to give the best answer, which I predict will be "use something other than jQuery", but there are some rare exceptions.

**Comment by lmj0011** [comment]
If you're trying to include JQuery inside vue component then SSR is causing that error

best way to include JQuery, is in the nuxt config like this:
https://github.com/nuxt/adonuxt/blob/master/config/nuxt.js

example
```js
  head: {
    title: 'Adonuxt',
    meta: [
      {
        charset: 'utf-8'
      },
      {
        name: 'viewport',
        content: 'width=device-width, initial-scale=1'
      },
      {
        hid: 'description',
        name: 'description',
        content: 'Adonuxt project'
      }
    ],
    link: [
      {
        rel: 'icon',
        type: 'image/x-icon',
        href: 'favicon.ico'
      },
    script: [
      {
        src: 'https://code.jquery.com/jquery-3.1.1.slim.min.js'
      }
    ]
  },
```

this way it's globally available
