### ISSUE TITLE
Add lang attribute to html wrapper

### ISSUE THREAD

**Issue by warrebuysse** [nuxt/adonuxt#41]
Is it possible to add the lang="nl" property to the <html> wrapper via the nuxt.js config?

**Comment by cayaner** [comment]
@warrebuysse  you can set it like so :

![screenshot from 2017-06-02 13-08-45](https://cloud.githubusercontent.com/assets/19613212/26721534/ab3b254a-4738-11e7-8bd9-5a9b3156677f.png)

**Comment by warrebuysse** [comment]
Works!
