### ISSUE TITLE
Vuetify integration

### ISSUE THREAD

**Issue by Pioruniasty** [nuxt/adonuxt#47]
Hi,

Today I decided to integrate Vuetify to my adonuxt project and I got this:

```
 ERROR  Failed to compile with 1 errors                                           20:31:04

This dependency was not found:

* vuetify in ./~/babel-loader/lib?{"presets":["vue-app"],"babelrc":false,"cacheDirectory":true}!./~/vue-loader/lib/selector.js?type=script&index=0!./resources/layouts/admin.vue

To install it, you can run: npm install --save vuetify
```

I put my 
```
import Vuetify from 'vuetify'
```

into admin.vue file. That's it. Nothing more. Of course i installed it via yarn add vuetify (and yarn add vuetify --dev).
Why this is not working?

**Comment by motia** [comment]
You did not install the `Vuetify` plugin into vue, add the following to `admin.vue`
    
    import Vuetify from 'vuetify'
    import Vue from 'vue
    
    Vue.use(Vuetify)

**Comment by Pioruniasty** [comment]
My full code

```
<template>
    <div>
        <h1>Panel administracyjny</h1>
        <nuxt />
    </div>
</template>

<script>
import Vue from 'vue'
import Vuetify from 'vuetify'

Vue.use(Vuetify)

export default {
    
}
</script>
```

Still the same error.

**Comment by Pioruniasty** [comment]
Ok, I'm fuckin stupid ...
I installed vuetify into ~ folder. New tab in iterm fckd up everything :D .

**Comment by digitalit** [comment]
@pawel-miczka , are you happy with Vuetify?

**Comment by pawel-miczka** [comment]
Damn right I am :D
