### ISSUE TITLE
Get current user within nuxtServerInit

### ISSUE THREAD

**Issue by kingdido999** [nuxt/adonuxt#6]
I'm not sure how to get user from request session within [nuxtServerInit](https://nuxtjs.org/guide/vuex-store#the-nuxtserverinit-action) method if the user is logged in via [Session Based Authentication](http://adonisjs.com/docs/3.2/authentication#_session_based_authentication). This is a part of my `store/index.js`:

```js
import Vue from 'vue'
import Vuex from 'vuex'
import axios from 'axios'

Vue.use(Vuex)

const store = new Vuex.Store({

  state: {
    authUser: null,
  },

  mutations: {
    SET_USER: function (state, user) {
      state.authUser = user
    }
  },

  actions: {

    nuxtServerInit ({ commit }, { req }) {
      // req.session is not defined
      if (req.session && req.session.authUser) {
        commit('SET_USER', req.session.authUser)
      }
    },

    // ...
```

I also tried to get it from an API call within `nuxtServerInit` but it doesn't work:

```js
    nuxtServerInit ({ commit }) {
      return Promise.resolve(axios.post('/api/checkLogin')
        .then(res => {
          commit('SET_USER', res.data)
        }))
    },
```

Errors showed up in browser console:

```
vue.runtime.common.js:521 [Vue warn]: The client-side rendered virtual DOM tree is not matching server-rendered content. This is likely caused by incorrect HTML markup, for example nesting block-level elements inside <p>, or missing <tbody>. Bailing hydration and performing full client-side render. 

[nuxt.js] Cannot load components TypeError: Cannot read property 'toLowerCase' of undefined
    at emptyNodeAt (vue.runtime.common.js:4093)
    at VueComponent.patch [as __patch__] (vue.runtime.common.js:4600)
    at VueComponent.Vue._update (vue.runtime.common.js:2635)
    at VueComponent.updateComponent (vue.runtime.common.js:2609)
    at Watcher.get (vue.runtime.common.js:2934)
    at new Watcher (vue.runtime.common.js:2926)
    at VueComponent.Vue._mount (vue.runtime.common.js:2608)
    at VueComponent.0.Vue$2.$mount (vue.runtime.common.js:6178)
    at init (vue.runtime.common.js:1740)
    at hydrate (vue.runtime.common.js:4496)
```

**Comment by alexchopin** [comment]
Hi,
This is because we don't pass `request.auth` through nuxt params in the [app/Http/Controllers/NuxtController.js](https://github.com/nuxt/adonuxt/blob/master/template/app/Http/Controllers/NuxtController.js#L19)

You can customize the render function into your NuxtController.js:
```js
  * render (request, response) {
    request.request.auth = request.auth
    this.nuxt.render(request.request, response.response)
  }
}
```

and the use it in your nuxtServerInit function:
```js
    nuxtServerInit ({ commit }, { req }) {
      console.log(req.auth)
    },
```

**Comment by kingdido999** [comment]
@alexchopin Thank you!

**Comment by kingdido999** [comment]
I'm having a weird issue that after I logout the user, it comes to nuxt render function and the user is again logged in.

My `routes.js`:

```js
const Route = use('Route')

Route.post('/api/login', 'UserController.login')
Route.post('/api/logout', 'UserController.logout')
Route.post('/api/signup', 'UserController.store')

Route.any('*', 'NuxtController.render')
```

My logout function:

```js
  * logout (request, response) {
    console.log(`before logout isLoggedIn: ${yield request.auth.check()}`)
    yield request.auth.logout()
    console.log(`after logout isLoggedIn: ${yield request.auth.check()}`)
  }
```

nuxt's render function:

```js
  * render (request, response) {
    console.log(`nuxt render isLoggedIn: ${yield request.auth.check()}`)
    this.nuxt.render(request.request, response.response)
  }
```

Console output:

```
before logout isLoggedIn: true
after logout isLoggedIn: false
nuxt render isLoggedIn: true
```

Where could possibly go wrong?

**Comment by Atinux** [comment]
Hi @kingdido999 

I tried on my end and it works perfectly with the session authenticator.

**Comment by kingdido999** [comment]
@Atinux It works after I changed the session driver from `cookie` to `file`. Still very confused why cookie session does not work for me...

**Comment by lmj0011** [comment]
@alexchopin 
A way to pass server rendered data to the client?

```js
  * render (request, response) {
    request.request.auth = request.auth
    this.nuxt.render(request.request, response.response)
  }
}
```

**Comment by alexchopin** [comment]
Like I wrote before, you can overwrite `request.request` to pass data to the client, but those data will be available only when the client load the page not when the route of the webapp has changed.
In this case you need to use an API call.

**Comment by vaggelis2018** [comment]
What about adonis v.4.0?

**Comment by prince30** [comment]
@alexchopin I did the above mentioned things, but every time I refresh the page , the user gets logged out and i get null on doing req.auth.user

I am setting remember to true while loging in , but still the session ends on refreshing the page . Please help
