### ISSUE TITLE
How nuxt.js fetch and render data from DB

### ISSUE THREAD

**Issue by ruslankonev** [nuxt/adonuxt#7]
How to recieve data from adonis, without ajax requests? With use nuxt ssr?

**Comment by GustavsR** [comment]
@ruslankonev You have closed this issue, but have you found a solution? Please share it with others.

**Comment by ruslankonev** [comment]
@GustavsR you need to use Vuex or other promise based state/store provider. I still need to resolve this issue in Vuex way, but I have not resolve yet. As soon as I'll get a solution, I will show you the version of the decision.
